version: "3.9"
services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "8443:443"
    networks:
      - inception
    restart: always
  mariadb:
      build: ./requirements/mariadb
      image: mariadb
      env_file:
        - .env
      volumes:
        - mariadb_data:/var/lib/mysql
      networks:
        - inception
      restart: always
      services:
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
networks:
  inception:
    driver: bridge
# FIX THIS before submission
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ~/goinfre/data/mariadb
      o: bind
# FIX THIS before submission
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/mhashir/data/wordpress
      o: bind

